spring:
  application:
    name: OpenDataExtractors

app:
  configs:
    comum:
      dir-saida-arquivos: "/home/out/Desktop/"
      metainfos:
        versao: "1.1.0-BETA.1"
    municipios:
      metainfos:
        site: "https://github.com/rgiaviti/open-data/blob/master/censo/municipios.json"
        fontes: "IBGE"
        data-referencia: "2020-07-01"
    ufs:
      metainfos:
        site: "https://github.com/rgiaviti/open-data/blob/master/censo/ufs.json"
        fontes: "IBGE, Constituição Federal do Brasil, Senado Federal"
        data-referencia: "2020-07-01"
    empresas-b3:
      metainfos:
        site: "https://github.com/rgiaviti/open-data/blob/master/economia/b3/empresas-listadas.json"
        fontes: "B3 - Brasil, Bolsa, Balcão"

