spring:
  application:
    name: OpenDataExtractors

app:
  configs:
    comum:
      dir-saida-arquivos: "/home/rgiaviti/Desktop/"
      metainfos:
        versao: "1.1.0-BETA.1"
    municipios:
      metainfos:
        site: "https://github.com/rgiaviti/open-data/blob/master/censo/municipios.json"
        fontes: "IBGE"
        data-referencia: "2020-07-01"
    ufs:
      metainfos:
        site: "https://github.com/rgiaviti/open-data/blob/master/censo/ufs.json"
        fontes: "IBGE, Constituição Federal do Brasil, Senado Federal"
        data-referencia: "2020-07-01"
    empresas-b3:
      metainfos:
        site: "https://github.com/rgiaviti/open-data/blob/master/economia/b3/empresas-listadas.json"
        fontes: "B3 - Brasil Bolsa Balcão"
    fiis-b3:
      metainfos:
        site: "https://github.com/rgiaviti/open-data/blob/master/economia/b3/fundos-imobiliarios-listados.json"
        fontes: "B3 - Brasil Bolsa Balcão"
    bacen:
      ipca:
        metainfos:
          fontes: "IBGE, Banco Central do Brasil"
          site: "https://github.com/rgiaviti/open-data/blob/master/economia/inflacao/ipca.json"
      inpc:
        metainfos:
          fontes: "IBGE, Banco Central do Brasil"
          site: "https://github.com/rgiaviti/open-data/blob/master/economia/inflacao/inpc.json"
      igpm:
        metainfos:
          fontes: "FGV, Banco Central do Brasil"
          site: "https://github.com/rgiaviti/open-data/blob/master/economia/inflacao/igpm.json"
      selic:
        metainfos:
          fontes: "COPOM, Banco Central do Brasil"
          site: "https://github.com/rgiaviti/open-data/blob/master/economia/juros/selic.json"
      cdi:
        metainfos:
          fontes: "CETIP, Banco Central do Brasil"
          site: "https://github.com/rgiaviti/open-data/blob/master/economia/juros/cdi.json"
  infra:
    html:
      user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"